// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCjtjVhdXUBK-lH9DjLpxtf5d9_Ilgqw',
    appId: '1:869797165677:web:fe094eb9d81661c3da5d64',
    messagingSenderId: '869797165677',
    projectId: 'farm-harvest-3fd91',
    authDomain: 'farm-harvest-3fd91.firebaseapp.com',
    storageBucket: 'farm-harvest-3fd91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgj4-qR131toUhnel3LpKx_fkXllApI3Y',
    appId: '1:869797165677:android:b6b46f02c1b3e286da5d64',
    messagingSenderId: '869797165677',
    projectId: 'farm-harvest-3fd91',
    storageBucket: 'farm-harvest-3fd91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPSrUoJ4iCNaXsEd7IKiyRZZyRqM-oqdI',
    appId: '1:869797165677:ios:3eb6fb90d8ab25f1da5d64',
    messagingSenderId: '869797165677',
    projectId: 'farm-harvest-3fd91',
    storageBucket: 'farm-harvest-3fd91.appspot.com',
    iosBundleId: 'com.example.farmHarvest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPSrUoJ4iCNaXsEd7IKiyRZZyRqM-oqdI',
    appId: '1:869797165677:ios:3eb6fb90d8ab25f1da5d64',
    messagingSenderId: '869797165677',
    projectId: 'farm-harvest-3fd91',
    storageBucket: 'farm-harvest-3fd91.appspot.com',
    iosBundleId: 'com.example.farmHarvest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHCjtjVhdXUBK-lH9DjLpxtf5d9_Ilgqw',
    appId: '1:869797165677:web:23c9d89de4bad566da5d64',
    messagingSenderId: '869797165677',
    projectId: 'farm-harvest-3fd91',
    authDomain: 'farm-harvest-3fd91.firebaseapp.com',
    storageBucket: 'farm-harvest-3fd91.appspot.com',
  );
}
